### ISSUE TITLE
Conflicting licenses

### ISSUE THREAD

**Issue by Graham42** [tony41780/JQueryRC4#1]
In the [JQueryRC4.js](https://github.com/tony41780/JQueryRC4/blob/master/JQueryRC4.js) file it says "released under the terms of the Gnu Public License" but the [LICENSE file](https://github.com/tony41780/JQueryRC4/blob/master/MIT-LICENSE.txt) is an MIT license.

**Comment by tony41780** [comment]
The licensing disparity has been corrected.  Both files reflect the MIT license.
